name: Run daily script

on:
  schedule:
    - cron: "0 0 * * *" # midnight UTC every day
  workflow_dispatch: # lets you run manually too

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Run script
        env:
          YOUTUBE_API: ${{ secrets.YOUTUBE_API }}
        run: bun run scripts/updateTuberData.js